### ISSUE TITLE
Plugin failed to load.

### ISSUE THREAD

**Issue by Kr3m** [Psykotikism/No_Friendly-Fire#5]
sm plugins load "no_friendly-fire"
[SM] Plugin no_friendly-fire.smx failed to load: Unable to open file.
b sm plugins load "no_friendly-fire"
L 09/03/2021 - 22:30:33: [SM] Exception reported: Entity 1 (1) is invalid
L 09/03/2021 - 22:30:33: [SM] Blaming: no_friendly-fire.smx
L 09/03/2021 - 22:30:33: [SM] Call stack trace:
L 09/03/2021 - 22:30:33: [SM]   [0] GetEntPropString
L 09/03/2021 - 22:30:33: [SM]   [1] Line 112, no_friendly-fire.sp::OnPluginStart
[SM] Plugin no_friendly-fire.smx failed to load: Error detected in plugin startup (see error logs).
sm plugins load "no_friendly-fire"."s"m"x"
L 09/03/2021 - 22:31:12: [SM] Exception reported: Entity 1 (1) is invalid
L 09/03/2021 - 22:31:12: [SM] Blaming: no_friendly-fire.smx
L 09/03/2021 - 22:31:12: [SM] Call stack trace:
L 09/03/2021 - 22:31:12: [SM]   [0] GetEntPropString
L 09/03/2021 - 22:31:12: [SM]   [1] Line 112, no_friendly-fire.sp::OnPluginStart
[SM] Plugin no_friendly-fire.smx failed to load: Error detected in plugin startup (see error logs).

**Comment by Kr3m** [comment]
It seems this only happens when I try to load the plugin from the console.  Restarting the server allows the plugin to load.  Also, I was accessing the console from the LinuxGSM "~/l4d2server console" script so I'm not sure if it would be any different from the game console versus SSH.  Using the same command after restarting the servers seems to work correctly.

sm plugins load "no_friendly-fire"
[SM] Plugin no_friendly-fire.smx is already loaded.

**Comment by Psykotikism** [comment]
You said the plugin was initially disabled when the server started up. That means the error is happening when the plugin is loaded late. The only reason there's no error after you restarted the server is because the plugin loaded on server startup, but the issue you reported is still valid. I'll look into this and release an update eventually. Thanks for the report. I'll keep this open until I release an update or you can close it if you want.

**Comment by Kr3m** [comment]
Just to be clear, when I downloaded it last night, I had no issues loading the plugin.  After I moved the plugin to the disabled folder, restarted the servers, moved it back to the plugins folder and tried loading it from console is when the issue started until I restarted the server.  Not sure if that helps.

**Comment by Psykotikism** [comment]
Yes, that falls under the term "late-loading" because all plugins are loaded on server startup unless you disable them (move them to "disabled" folder). Any plugins that are loaded during runtime are considered as "late-loaded plugins."

I have released an update to address this issue. Closing this issue now.
